language: clojure
lein: lein2
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk7
#  - openjdk8	# Not yet available on the travis build machines
  - oraclejdk7
  - oraclejdk8
