<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="persons"
    nsURI="http://persons/1.0" nsPrefix="persons">
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" lowerBound="2"
        upperBound="2" eType="#//Person" eOpposite="#//Person/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/parents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genealogy" lowerBound="1"
        eType="#//Genealogy" eOpposite="#//Genealogy/persons"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ageGroup" eType="#//AgeGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" lowerBound="1"
        eType="#//Address" eOpposite="#//Address/person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Male" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wife" eType="#//Female"
        eOpposite="#//Female/husband"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Female" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="husband" eType="#//Male"
        eOpposite="#//Male/wife"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Genealogy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true" eOpposite="#//Person/genealogy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgeGroup">
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="ADULT" value="1"/>
    <eLiterals name="CHILD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/address"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="town" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
