<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pmtest" nsURI="http://pmtest/1.0" nsPrefix="pmtest">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="i" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" upperBound="-1" eType="#//A"
        eOpposite="#//A/s"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s" upperBound="-1" eType="#//A"
        eOpposite="#//A/t"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="d" upperBound="-1" eType="#//D"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//A"/>
  <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//A"/>
  <eClassifiers xsi:type="ecore:EClass" name="D">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="j" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
